services:
  server:
    build:
      context: .
      target: build-release-stage
    ports:
      - 8090:8090
    volumes:
      - db_data:/app/data
    environment:
      - DATABASE_PATH=/app/data/app.db

# Example Postgres extension
#     depends_on:
#       db:
#         condition: service_healthy
#   db:
#     image: postgres
#     restart: always
#     user: postgres
#     secrets:
#       - db-password
#     volumes:
#       - db-data:/var/lib/postgresql/data
#     environment:
#       - POSTGRES_DB=example
#       - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
#     expose:
#       - 5432
#     healthcheck:
#       test: [ "CMD", "pg_isready" ]
#       interval: 10s
#       timeout: 5s
#       retries: 5
# secrets:
#   db-password:
#     file: db/password.txt

volumes:
  db_data:

