services:
  server:
    build:
      context: .
      target: build-release-stage
    ports:
      - 8090:8090
    volumes:
      - db_data:/app/data

# Example Postgres extension
#     depends_on:
#       db:
#         condition: service_healthy
#   db:
#     image: postgres
#     ...

volumes:
  db_data:

